apiVersion: apps/v1
kind: Deployment
metadata:
  name: onguard
  labels:
    app: onguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onguard
  template:
    metadata:
      labels:
        app: onguard
    spec:
      containers:
      - name: onguard
        image: onguard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DB_REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: exhort-onguard-secret
                key: db.host
          - name: DB_REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: exhort-onguard-secret
                key: db.port
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 9000
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: onguard
  labels:
    app: onguard
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: onguard
