apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:latest
        imagePullPolicy: Always
        ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP
        env:
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongodb-creds
                key: mongodb-database
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-creds
                key: mongodb-password
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-creds
                key: mongodb-username
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-creds
                key: mongodb-root-password               
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb